### ISSUE TITLE
~deleteall falls over with "has_more"

### ISSUE THREAD

**Issue by jonobrien** [Omodi/GoToBot#60]
# Bug
Doesn't delete the messages in private group message with first call, but second call to `~deleteall` seems to delete messages, but still fails on has_more, in a different public channel than originally called from, and which bot was not whitelisted in,

## steps to reproduce
1. invite bot
2. send a command
3. deleteall
4. check logs

```
2017-07-26T14:56:04.117537+00:00 app[bot.1]: deleting all messages in private groups, ims, public channels
...
2017-07-26T14:56:33.387432+00:00 app[bot.1]: no messages to delete in: C<id_here> -> <name_here>
...
2017-07-26T14:57:54.149678+00:00 app[bot.1]: deleting messages in channel: C<id_here> -> <name_here>
2017-07-26T14:58:17.554456+00:00 app[bot.1]: [!!] uncaught error
2017-07-26T14:58:17.556530+00:00 app[bot.1]: Traceback (most recent call last):
2017-07-26T14:58:17.556586+00:00 app[bot.1]:   File "gotobot.py", line 170, in startBot
2017-07-26T14:58:17.556588+00:00 app[bot.1]:     r["callback"](self, msg)
2017-07-26T14:58:17.556609+00:00 app[bot.1]:   File "gotobot.py", line 311, in deleteAll
2017-07-26T14:58:17.556611+00:00 app[bot.1]:     for message in msgJson["messages"]: # collect remaining history
2017-07-26T14:58:17.556666+00:00 app[bot.1]: KeyError: 'messages'
2017-07-26T14:58:17.556695+00:00 app[bot.1]: [!!] restarting the bot
2017-07-26T14:58:23.489869+00:00 app[bot.1]: connected
```
seems to be fine after a second call
```
2017-07-26T15:08:01.379390+00:00 app[bot.1]: deleting all messages in private groups, ims, public channels
...
2017-07-26T15:08:26.208417+00:00 app[bot.1]:   deleting group messages in: G<id_here> -> <name_here>
2017-07-26T15:08:26.766844+00:00 app[bot.1]: deleted: 1501081654.629823
2017-07-26T15:08:27.030848+00:00 app[bot.1]: deleted: 1501080878.122009
2017-07-26T15:08:27.246905+00:00 app[bot.1]: deleted: 1501080788.063685
```
same keyError again after deleting the messages.

**Comment by jonobrien** [comment]
culprit here [311](https://github.com/Omodi/GoToBot/blob/master/gotobot.py#L311)
